Models/Product.cs
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Project.Models
{
    public class Product
    {
        [Key]
        public int ProductId { get; set; }
        [Required]
        [StringLength(100)]
        public string Name { get; set; }
        [Required]
        public string Description { get; set; }
        [Required]
        [Display(Name ="Stock Quantity")]
        public int StockQuantity { get; set; }
        [Required]
        [Display(Name ="Unitary Amount")]
        public int UnitaryAmount { get; set; }
        [Required]
        public Level Level { get; set; }
        public string Image { get; set; }

        [Display(Name = "Image")]
        [Required]
        [NotMapped]
        [DataType(DataType.Upload)]
        public IFormFile ImageFile { get; set; }
        public ICollection<Request> Requests { get; set; }
    }
    public enum Level
    {
        Zero,One,Two
    }
}

Controllers/ProductController.cs
#nullable disable
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Project.Data;
using Project.Models;

namespace Project.Controllers
{
    [Authorize]
    public class ProductController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _WebHostEnvironment;

        public ProductController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _WebHostEnvironment = webHostEnvironment;
        }

        [Authorize]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Products.ToListAsync());
        }

        /*
         public IActionResult Index()
        {
            //var products = _context.Products.ToList();

            return View(_context.Products.ToList());
        }
         */

        [Authorize]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        [Authorize(Roles = "Admin, Coordinator")]
        // GET: Products/Create/
        public IActionResult Create()
        {
            return View();
        }
        // POST: Product/Create
        [Authorize(Roles = "Admin, Coordinator")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Product product)
        {
            if (ModelState.IsValid)
            {
                string rootPath = _WebHostEnvironment.WebRootPath;
                string path = @"\Uploads\";

                string fileName = Path.GetFileNameWithoutExtension(product.ImageFile.FileName);
                string extension = Path.GetExtension(product.ImageFile.FileName);

                product.Image = fileName = fileName + DateTime.Now.ToString("yyyymmssfff") + extension;

                string pathforSave = Path.Combine(rootPath + path + fileName);
                using (var fileStream = new FileStream(pathforSave, FileMode.Create))
                {
                    product.ImageFile.CopyTo(fileStream);
                }

                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }
        // GET: Products/Edit/5
        [Authorize(Roles = "Admin, Coordinator")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }

        // POST: Products/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Coordinator")]
        public async Task<IActionResult> Edit(int id, Product product)
        {
            if (id != product.ProductId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var objfromDb = _context.Products.AsNoTracking().FirstOrDefault(a => a.ProductId == id);

                    if (product.ImageFile != null)
                    {
                        string rootPath = _WebHostEnvironment.WebRootPath;
                        string path = @"\Uploads\";

                        string fileName = Path.GetFileNameWithoutExtension(product.ImageFile.FileName);
                        string extension = Path.GetExtension(product.ImageFile.FileName);

                        product.Image = fileName = fileName + DateTime.Now.ToString("yyyymmssfff") + extension;

                        string pathforSave = Path.Combine(rootPath + path + fileName);

                        var oldImage = Path.Combine(rootPath + path, objfromDb.Image);
                        if (System.IO.File.Exists(oldImage))
                        {
                            System.IO.File.Delete(oldImage);
                        }

                        using (var fileStream = new FileStream(pathforSave, FileMode.Create))
                        {
                            product.ImageFile.CopyTo(fileStream);
                        }
                    }
                    else
                    {
                        product.Image = objfromDb.Image;
                    }
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.ProductId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        // GET: Products/Delete/5
        [Authorize(Roles = "Admin, Coordinator")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "Admin, Coordinator")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product = await _context.Products.FindAsync(id);
            _context.Products.Remove(product);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id)
        {
            return _context.Products.Any(e => e.ProductId == id);
        }
    }
}

Controllers/RequestController.cs
#nullable disable
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Project.Data;
using Project.Models;

namespace Project.Controllers
{
    [Authorize]
    public class RequestController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public RequestController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
        public IActionResult Index()
        {
            var requests=new List<Request>();

            if (User.IsInRole(WC.AdminRole) || User.IsInRole(WC.CoordinatorRole))
            {
                //Console.WriteLine("cenas");
                requests = _context.Requests.Include(a=>a.Product).Include(a => a.ApplicationUser).ToList();
            }
            
            else
            {
                //Console.WriteLine("cenas2");
                requests = _context.Requests.Where(a => a.ApplicationUser.Id == _userManager.GetUserId(User)).Include(a => a.Product).Include(a => a.ApplicationUser).ToList();
            }

            return View(requests);
        }
        [HttpGet]
        public async Task<IActionResult> Create(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var product = _context.Products.FirstOrDefault(a => a.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }
            Request request = new Request()
            {
                Product=product,
                ProductId=product.ProductId,
                ApplicationUser =await _userManager.GetUserAsync(HttpContext.User),
                ApplicationUserId =_userManager.GetUserId(User)
            };
            return View(request);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Models.Request rvm)
        {
            if (ModelState.IsValid)
            {
                Request req = new Request();
                req.ProductId = rvm.ProductId;
                req.RequestDate = DateTime.Now;
                req.QuantityRequest = rvm.QuantityRequest;
                req.ApplicationUserId = _userManager.GetUserId(User);
                req.Justification = rvm.Justification;
                req.Note = rvm.Note;

                Product product = _context.Products.FirstOrDefault(a => a.ProductId == rvm.ProductId);

                req.TotalAmount = rvm.QuantityRequest * product.UnitaryAmount;

                var stock = product.StockQuantity;
                if (rvm.QuantityRequest > stock)
                {
                    req.RequestStatus = Status.PENDING;
                }
                else
                {
                    if (product.Level == Level.Zero)
                    {
                        req.RequestStatus = Status.APPROVED;

                        product.StockQuantity = product.StockQuantity - req.QuantityRequest;
                    }
                    else if (product.Level == Level.One)
                    {
                        if (User.IsInRole(WC.CoordinatorRole))
                        {
                            req.RequestStatus = Status.APPROVED;
                            product.StockQuantity = product.StockQuantity - req.QuantityRequest;
                        }
                        else
                        {
                            req.RequestStatus = Status.PENDING;
                            product.StockQuantity = product.StockQuantity - req.QuantityRequest;
                        }
                    }
                    else
                    {
                        if (User.IsInRole(WC.CoordinatorRole))
                        {
                            req.RequestStatus = Status.PARTIAL;
                            product.StockQuantity = product.StockQuantity - req.QuantityRequest;
                        }
                        else
                        {
                            req.RequestStatus = Status.PENDING;
                            product.StockQuantity = product.StockQuantity - req.QuantityRequest;
                        }
                    }
                }
                _context.Requests.Add(req);
                _context.Products.Update(product);
                _context.SaveChanges();

                return RedirectToAction("Index");
            }
            var prod = _context.Products.FirstOrDefault(a => a.ProductId == rvm.ProductId);
            
            Request request = new Request()
            {
                ProductId = prod.ProductId
            };
            return View(request);
        }
        [HttpGet]
        [Authorize]
        public IActionResult UpdateStatus(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var request = _context.Requests.FirstOrDefault(a=>a.RequestId==id);
            if (request == null)
            {
                return NotFound();
            }
            return View(request);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult UpdateStatus(int id,Request request)
        {
            if (id != request.RequestId)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                var objFromDB = _context.Requests.FirstOrDefault(a => a.RequestId == id);
                if (objFromDB == null)
                {
                    return NotFound();
                }
                objFromDB.RequestStatus = request.RequestStatus;

                _context.Update(objFromDB);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(request);
        }
        [Authorize(Roles = "Admin, Coordinator")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var request = await _context.Requests
                .FirstOrDefaultAsync(m => m.RequestId == id);
            if (request == null)
            {
                return NotFound();
            }
            return View(request);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "Admin, Coordinator")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var request = await _context.Requests.FindAsync(id);
            _context.Requests.Remove(request);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

Views/Product/Create.cshtml
@model Project.Models.Product
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row">
    <div class="col-12">
        <h1 class="text-center text-info">@ViewData["Title"]</h1>
        <hr />
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row">
                <div class="col-4">
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-4">
                    <div class="form-group">
                        <label asp-for="Description" class="control-label"></label>
                        <input asp-for="Description" class="form-control" />
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-4">
                    <div class="form-group">
                        <label asp-for="StockQuantity" class="control-label"></label>
                        <input asp-for="StockQuantity" class="form-control" />
                        <span asp-validation-for="StockQuantity" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-4">
                    <div class="form-group">
                        <label asp-for="UnitaryAmount" class="control-label"></label>
                        <input asp-for="UnitaryAmount" class="form-control" />
                        <span asp-validation-for="UnitaryAmount" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-4">
                    <div class="form-group">
                        <label asp-for="Level" class="control-label"></label>
                        <select asp-for="Level" class="form-select" asp-items="Html.GetEnumSelectList<Level>()"></select>
                    </div>
                </div>
                <div class="col-4">
                    <div class="form-group">
                        <label asp-for="ImageFile" class="control-label"></label>
                        <div class="input-group">
                            <input  asp-for="ImageFile" class="form-control">
                        </div>
                        <span asp-validation-for="ImageFile" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <br />
            <div class="row">
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary btn-sm" />
                     <a asp-action="Index" class="btn btn-warning btn-sm">Back to List</a>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Product/Delete.cshtml
@model Project.Models.Product

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-12">
        <h1 class="text-info text-center">Delete</h1>
        <hr />
        <h4 class="text-warning text-center">Are you sure you want to delete this?</h4>
        <div class="row d-flex align-item-center justify-content-center">
            <div class="col-4 text-center">
                <label class="fw-bold">@Model?.Name</label>
                <br />
                <div class="border p-1">
                    <img src="~/Uploads/@Model?.Image" width="344" height="200"/>
                </div>
                <form asp-action="Delete">
                    <input type="hidden" asp-for="ProductId" />
                    <div class="row">
                        <div class="form-group">
                            <input type="submit" value="Delete" class="btn btn-danger btn-sm" />
                            <a asp-action="Index" class="btn btn-warning btn-sm">Back to List</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

Views/Product/Details.cshtml
@model Project.Models.Product

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row d-flex align-item-center justify-content-center">
    <div class="col-6">
        <h1 class="text-center text-info">Product Details</h1>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Name)
            </dt>
            <dd class="col-sm-10 text-center">
                @Html.DisplayFor(model => model.Name)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Description)
            </dt>
            <dd class="col-sm-10 text-center">
                @Html.DisplayFor(model => model.Description)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.UnitaryAmount)
            </dt>
            <dd class="col-sm-10 text-center">
                @Html.DisplayFor(model => model.UnitaryAmount)
            </dd>
             <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.StockQuantity)
            </dt>
            <dd class="col-sm-10 text-center">
                @Html.DisplayFor(model => model.StockQuantity)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Level)
            </dt>
            <dd class="col-sm-10 text-center">
                @Html.DisplayFor(model => model.Level)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Image)
            </dt>
            <dd class="col-sm-10">
                <img src="~/Uploads/@Model?.Image" width="350" height="270" />
            </dd>
        </dl>
        <div class="row">
            <div class="col-12 d-flex align-item-center justify-content-center">
                <a asp-action="Create" asp-controller="Request" asp-route-id="@Model?.ProductId" class="btn btn-success btn-sm mx-1">Acquire</a>
                <a asp-action="Index" class="btn btn-warning btn-sm mx-1">Back to List</a>
            </div>
        </div>
    </div>
</div>

Views/Product/Edit.cshtml
@model Project.Models.Product

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-12">
        <h1 class="text-center text-info">@ViewData["Title"]</h1>
        <hr />
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ProductId" />
            <div class="row">
                <div class="col-4">
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-4">
                    <div class="form-group">
                        <label asp-for="Description" class="control-label"></label>
                        <input asp-for="Description" class="form-control" />
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-4">
                    <div class="form-group">
                        <label asp-for="StockQuantity" class="control-label"></label>
                        <input asp-for="StockQuantity" class="form-control" />
                        <span asp-validation-for="StockQuantity" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-4">
                    <div class="form-group">
                        <label asp-for="UnitaryAmount" class="control-label"></label>
                        <input asp-for="UnitaryAmount" class="form-control" />
                        <span asp-validation-for="UnitaryAmount" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-4">
                    <div class="form-group">
                        <label asp-for="Level" class="control-label"></label>
                        <select asp-for="Level" class="form-select" asp-items="Html.GetEnumSelectList<Level>()"></select>
                    </div>
                </div>
                 <div class="col-4">
                    <div class="form-group">
                        <label asp-for="ImageFile" class="control-label"></label>
                        <div class="input-group">
                            <input  asp-for="ImageFile" class="form-control">
                        </div>
                        <span asp-validation-for="ImageFile" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <br />
             <div class="row">
                <div class="form-group">
                    <input type="submit" value="Update" class="btn btn-primary btn-sm" />
                     <a asp-action="Index" class="btn btn-warning btn-sm">Back to List</a>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
}

Views/Product/Index.cshtml
@model IEnumerable<Project.Models.Product>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-12">
        <h1 class="text-center text-info">Our Products</h1>
        <hr />
        @if (User.IsInRole(WC.AdminRole))
        {
            <div class="row">
                <div class="col-12">
                    <a asp-action="Create" class="btn btn-success float-end">Create New</a>
                </div>
            </div>
        }

        <div class="row mt-2">
            @if (Model != null)
            {
                if (Model.Count() > 0)
                {
                    foreach (var item in Model)
                    {
                        <div class="col-lg-4 col-md-4 col-sm-6">
                            <div class="card shadow-sm">
                                <div class="card-body">
                                    <div class="row">
                                        <label class="fw-bold">Name:<span class="float-end">@item.Name</span></label>
                                    </div>
                                    <div class="row">
                                        <label class="fw-bold">
                                            Available in Stock:
                                            @if (item.StockQuantity > 0)
                                            {
                                                <span class="float-end">Yes</span>
                                            }
                                            else
                                            {
                                                <span class="float-end">No</span>
                                            }
                                        </label>
                                    </div>
                                    <div class="row">
                                        <label class="fw-bold">Unitary Amount:<span class="float-end">@item.UnitaryAmount</span></label>
                                    </div>
                                    <div class="row">
                                        <label class="fw-bold">Level:<span class="float-end">@item.Level</span></label>
                                    </div>
                                    <div class="row border p-1">
                                        <img src="~/Uploads/@item.Image" />
                                    </div>
                                    <div class="row mt-2">
                                        <div class="col-12 d-flex align-item-center justify-content-center">
                                            @if (User.IsInRole(WC.AdminRole))
                                            {
                                                <a asp-action="Edit" asp-route-id="@item.ProductId" class="btn btn-sm btn-primary mx-1">Edit</a>
                                            }
                                            <a asp-action="Details" asp-route-id="@item.ProductId" class="btn btn-sm btn-success mx-1">Details</a>
                                            @if (User.IsInRole(WC.AdminRole))
                                            {
                                                <a asp-action="Delete" asp-route-id="@item.ProductId" class="btn btn-sm btn-danger mx-1">Delete</a>
                                            }
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                }
                else
                {
                    <div class="alert alert-warning text-center">
                        No records found. Please add a record.
                    </div>
                }
            }
        </div>
    </div>
</div>